[package]
name = "asyncapi-rust-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "*"
rust-embed = "*"
serde = {version="*", features=["derive"]}
serde_yaml ="*"
